version: "3.8"
services:
  app:
    build:
      context: ./
      target: production
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DEBUG: express-docker:*
